; tpre2.g
; called before tool 2 is selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu May 13 2021 17:38:36 GMT+0200 (heure d’été d’Europe centrale)

; check that X and Y are homed in case the user press the load tool at first
M98 P"/sys/C28.1.g"
; check if a tool is already loaded (after hard reset for example)
if sensors.gpIn[1].value=1
    abort "Tool carriage is not empty"