; tpre0.g
; called before tool 0 is selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu May 13 2021 17:38:36 GMT+0200 (heure d’été d’Europe centrale)

; check that X and Y are homed in cas the user press the load tool at first
M98 P"C28.1.g"

; check if a tool is already loaded (after hard reset for example)
if sensors.gpIn[1].value=1
    abort