; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Feb 08 2021 23:53:40 GMT+0100 (heure normale d’Europe centrale)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


