; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Feb 08 2021 23:53:41 GMT+0100 (heure normale d’Europe centrale)

