; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Feb 08 2021 23:53:42 GMT+0100 (heure normale d’Europe centrale)
; Wait for set temperatures to be reached
M116 P0

